# databases:
#   - name: Bookme-app-db
#     databaseName: bookme_app_db
#     user: tibi
#     plan: free

services:
  - type: web
    name: bookme
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: Bookme-app-db
      #     property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
